# Generated by Django 5.0.4 on 2024-04-04 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managerkit", "0003_category_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disability",
            field=models.TextField(
                choices=[("Disable", "Disable"), ("Non-disable", "Non-disable")],
                default="-",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="medical_conditions",
            field=models.TextField(
                choices=[
                    ("No Medical Conditions", "No Conditions"),
                    ("Asthma", "Asthma"),
                    ("Diabetes", "Diabetes"),
                    ("Hypertension", "Hypertension"),
                    ("Allergies", "Allergies"),
                    ("Other", "Other"),
                ],
                default="-",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        99, message="Age must be below 100"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dietary_restrictions",
            field=models.TextField(
                choices=[
                    ("No Dietary Restrictions", "No Restrictions"),
                    ("FODMAP", "FODMAP"),
                    ("Gluten Free", "Gluten Free"),
                    ("Lactose Free", "Lactose Free"),
                    ("Nut Free", "Nut Free"),
                    ("Vegan", "Vegan"),
                    ("Vegetarian", "Vegetarian"),
                    ("Other", "Other"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("N", "Non-binary"),
                    ("T", "Trans"),
                    ("O", "Other"),
                ],
                max_length=1,
            ),
        ),
    ]
