# Generated by Django 5.0.4 on 2024-04-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerkit', '0003_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
