# Generated by Django 5.0.4 on 2024-04-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerkit', '0004_item_expiry_date'),
        ('managerkit', '0004_user_disability_user_medical_conditions_and_more'),
    ]

    operations = [
    ]
