# Generated by Django 5.0.4 on 2024-04-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managerkit", "0005_merge_20240405_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="relationship",
            field=models.TextField(
                choices=[
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Husband", "Husband"),
                    ("Wife", "Wife"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                    ("Brother", "Brother"),
                    ("Sister", "Sister"),
                    ("Cousin (male)", "Cousin (male)"),
                    ("Cousin (female)", "Cousin (female)"),
                    ("Nephew", "Nephew"),
                    ("Niece", "Niece"),
                    ("Grandfather", "Grandfather"),
                    ("Grandmother", "Grandmother"),
                    ("Grandson", "Grandson"),
                    ("Granddaughter", "Granddaugher"),
                    ("Other", "Other"),
                ],
                default="-",
            ),
            preserve_default=False,
        ),
    ]
