# Generated by Django 5.0.4 on 2024-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managerkit", "0006_user_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="-", max_length=254),
            preserve_default=False,
        ),
    ]
