# Generated by Django 5.0.4 on 2024-04-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managerkit", "0008_alter_item_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship",
            field=models.TextField(
                choices=[
                    ("Primary User", "Primary User"),
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Husband", "Husband"),
                    ("Wife", "Wife"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                    ("Brother", "Brother"),
                    ("Sister", "Sister"),
                    ("Cousin (male)", "Cousin (male)"),
                    ("Cousin (female)", "Cousin (female)"),
                    ("Nephew", "Nephew"),
                    ("Niece", "Niece"),
                    ("Grandfather", "Grandfather"),
                    ("Grandmother", "Grandmother"),
                    ("Grandson", "Grandson"),
                    ("Granddaughter", "Granddaugher"),
                    ("Other", "Other"),
                ]
            ),
        ),
    ]
